/* eslint-disable */
// Auto-generated by scripts/generate-public-media-manifest.mjs — do not edit.

export interface PublicImageVariant {
  readonly url: string;
  readonly width: number;
}

export interface PublicImage {
  readonly width: number;
  readonly height: number;
  readonly jpg: PublicImageVariant[];
  readonly webp: PublicImageVariant[];
  readonly avif: PublicImageVariant[];
}

export const heroGallery: PublicImage[] = [
  {
    "width": 6000,
    "height": 4000,
    "jpg": [
      {
        "url": "/_optimized/hero/1734066180384-503132957-640.jpg",
        "width": 640
      },
      {
        "url": "/_optimized/hero/1734066180384-503132957-960.jpg",
        "width": 960
      },
      {
        "url": "/_optimized/hero/1734066180384-503132957-1280.jpg",
        "width": 1280
      },
      {
        "url": "/_optimized/hero/1734066180384-503132957-1600.jpg",
        "width": 1600
      },
      {
        "url": "/_optimized/hero/1734066180384-503132957-1920.jpg",
        "width": 1920
      },
      {
        "url": "/_optimized/hero/1734066180384-503132957-6000.jpg",
        "width": 6000
      }
    ],
    "webp": [
      {
        "url": "/_optimized/hero/1734066180384-503132957-640.webp",
        "width": 640
      },
      {
        "url": "/_optimized/hero/1734066180384-503132957-960.webp",
        "width": 960
      },
      {
        "url": "/_optimized/hero/1734066180384-503132957-1280.webp",
        "width": 1280
      },
      {
        "url": "/_optimized/hero/1734066180384-503132957-1600.webp",
        "width": 1600
      },
      {
        "url": "/_optimized/hero/1734066180384-503132957-1920.webp",
        "width": 1920
      },
      {
        "url": "/_optimized/hero/1734066180384-503132957-6000.webp",
        "width": 6000
      }
    ],
    "avif": [
      {
        "url": "/_optimized/hero/1734066180384-503132957-640.avif",
        "width": 640
      },
      {
        "url": "/_optimized/hero/1734066180384-503132957-960.avif",
        "width": 960
      },
      {
        "url": "/_optimized/hero/1734066180384-503132957-1280.avif",
        "width": 1280
      },
      {
        "url": "/_optimized/hero/1734066180384-503132957-1600.avif",
        "width": 1600
      },
      {
        "url": "/_optimized/hero/1734066180384-503132957-1920.avif",
        "width": 1920
      },
      {
        "url": "/_optimized/hero/1734066180384-503132957-6000.avif",
        "width": 6000
      }
    ]
  }
];

export const featuredGallery: PublicImage[] = [
  {
    "width": 3280,
    "height": 4100,
    "jpg": [
      {
        "url": "/_optimized/gallery/featured/1734065395770-537681133-480.jpg",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/1734065395770-537681133-720.jpg",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/1734065395770-537681133-960.jpg",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/1734065395770-537681133-1200.jpg",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/1734065395770-537681133-3280.jpg",
        "width": 3280
      }
    ],
    "webp": [
      {
        "url": "/_optimized/gallery/featured/1734065395770-537681133-480.webp",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/1734065395770-537681133-720.webp",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/1734065395770-537681133-960.webp",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/1734065395770-537681133-1200.webp",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/1734065395770-537681133-3280.webp",
        "width": 3280
      }
    ],
    "avif": [
      {
        "url": "/_optimized/gallery/featured/1734065395770-537681133-480.avif",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/1734065395770-537681133-720.avif",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/1734065395770-537681133-960.avif",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/1734065395770-537681133-1200.avif",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/1734065395770-537681133-3280.avif",
        "width": 3280
      }
    ]
  },
  {
    "width": 4000,
    "height": 5000,
    "jpg": [
      {
        "url": "/_optimized/gallery/featured/1734065508950-385634406-480.jpg",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/1734065508950-385634406-720.jpg",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/1734065508950-385634406-960.jpg",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/1734065508950-385634406-1200.jpg",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/1734065508950-385634406-4000.jpg",
        "width": 4000
      }
    ],
    "webp": [
      {
        "url": "/_optimized/gallery/featured/1734065508950-385634406-480.webp",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/1734065508950-385634406-720.webp",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/1734065508950-385634406-960.webp",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/1734065508950-385634406-1200.webp",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/1734065508950-385634406-4000.webp",
        "width": 4000
      }
    ],
    "avif": [
      {
        "url": "/_optimized/gallery/featured/1734065508950-385634406-480.avif",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/1734065508950-385634406-720.avif",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/1734065508950-385634406-960.avif",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/1734065508950-385634406-1200.avif",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/1734065508950-385634406-4000.avif",
        "width": 4000
      }
    ]
  },
  {
    "width": 4000,
    "height": 6000,
    "jpg": [
      {
        "url": "/_optimized/gallery/featured/1734066160338-665205057-480.jpg",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/1734066160338-665205057-720.jpg",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/1734066160338-665205057-960.jpg",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/1734066160338-665205057-1200.jpg",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/1734066160338-665205057-4000.jpg",
        "width": 4000
      }
    ],
    "webp": [
      {
        "url": "/_optimized/gallery/featured/1734066160338-665205057-480.webp",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/1734066160338-665205057-720.webp",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/1734066160338-665205057-960.webp",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/1734066160338-665205057-1200.webp",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/1734066160338-665205057-4000.webp",
        "width": 4000
      }
    ],
    "avif": [
      {
        "url": "/_optimized/gallery/featured/1734066160338-665205057-480.avif",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/1734066160338-665205057-720.avif",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/1734066160338-665205057-960.avif",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/1734066160338-665205057-1200.avif",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/1734066160338-665205057-4000.avif",
        "width": 4000
      }
    ]
  },
  {
    "width": 3527,
    "height": 4409,
    "jpg": [
      {
        "url": "/_optimized/gallery/featured/1734066888247-726289103-480.jpg",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/1734066888247-726289103-720.jpg",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/1734066888247-726289103-960.jpg",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/1734066888247-726289103-1200.jpg",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/1734066888247-726289103-3527.jpg",
        "width": 3527
      }
    ],
    "webp": [
      {
        "url": "/_optimized/gallery/featured/1734066888247-726289103-480.webp",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/1734066888247-726289103-720.webp",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/1734066888247-726289103-960.webp",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/1734066888247-726289103-1200.webp",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/1734066888247-726289103-3527.webp",
        "width": 3527
      }
    ],
    "avif": [
      {
        "url": "/_optimized/gallery/featured/1734066888247-726289103-480.avif",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/1734066888247-726289103-720.avif",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/1734066888247-726289103-960.avif",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/1734066888247-726289103-1200.avif",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/1734066888247-726289103-3527.avif",
        "width": 3527
      }
    ]
  },
  {
    "width": 3414,
    "height": 4267,
    "jpg": [
      {
        "url": "/_optimized/gallery/featured/1734066888253-502748387-480.jpg",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/1734066888253-502748387-720.jpg",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/1734066888253-502748387-960.jpg",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/1734066888253-502748387-1200.jpg",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/1734066888253-502748387-3414.jpg",
        "width": 3414
      }
    ],
    "webp": [
      {
        "url": "/_optimized/gallery/featured/1734066888253-502748387-480.webp",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/1734066888253-502748387-720.webp",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/1734066888253-502748387-960.webp",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/1734066888253-502748387-1200.webp",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/1734066888253-502748387-3414.webp",
        "width": 3414
      }
    ],
    "avif": [
      {
        "url": "/_optimized/gallery/featured/1734066888253-502748387-480.avif",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/1734066888253-502748387-720.avif",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/1734066888253-502748387-960.avif",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/1734066888253-502748387-1200.avif",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/1734066888253-502748387-3414.avif",
        "width": 3414
      }
    ]
  },
  {
    "width": 3709,
    "height": 5563,
    "jpg": [
      {
        "url": "/_optimized/gallery/featured/CR7_9082-480.jpg",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9082-720.jpg",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9082-960.jpg",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9082-1200.jpg",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9082-3709.jpg",
        "width": 3709
      }
    ],
    "webp": [
      {
        "url": "/_optimized/gallery/featured/CR7_9082-480.webp",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9082-720.webp",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9082-960.webp",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9082-1200.webp",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9082-3709.webp",
        "width": 3709
      }
    ],
    "avif": [
      {
        "url": "/_optimized/gallery/featured/CR7_9082-480.avif",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9082-720.avif",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9082-960.avif",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9082-1200.avif",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9082-3709.avif",
        "width": 3709
      }
    ]
  },
  {
    "width": 4640,
    "height": 6960,
    "jpg": [
      {
        "url": "/_optimized/gallery/featured/CR7_9094-480.jpg",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9094-720.jpg",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9094-960.jpg",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9094-1200.jpg",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9094-4640.jpg",
        "width": 4640
      }
    ],
    "webp": [
      {
        "url": "/_optimized/gallery/featured/CR7_9094-480.webp",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9094-720.webp",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9094-960.webp",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9094-1200.webp",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9094-4640.webp",
        "width": 4640
      }
    ],
    "avif": [
      {
        "url": "/_optimized/gallery/featured/CR7_9094-480.avif",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9094-720.avif",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9094-960.avif",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9094-1200.avif",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9094-4640.avif",
        "width": 4640
      }
    ]
  },
  {
    "width": 4469,
    "height": 5586,
    "jpg": [
      {
        "url": "/_optimized/gallery/featured/CR7_9426-480.jpg",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9426-720.jpg",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9426-960.jpg",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9426-1200.jpg",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9426-4469.jpg",
        "width": 4469
      }
    ],
    "webp": [
      {
        "url": "/_optimized/gallery/featured/CR7_9426-480.webp",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9426-720.webp",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9426-960.webp",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9426-1200.webp",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9426-4469.webp",
        "width": 4469
      }
    ],
    "avif": [
      {
        "url": "/_optimized/gallery/featured/CR7_9426-480.avif",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9426-720.avif",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9426-960.avif",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9426-1200.avif",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9426-4469.avif",
        "width": 4469
      }
    ]
  },
  {
    "width": 3895,
    "height": 5842,
    "jpg": [
      {
        "url": "/_optimized/gallery/featured/CR7_9461-480.jpg",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9461-720.jpg",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9461-960.jpg",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9461-1200.jpg",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9461-3895.jpg",
        "width": 3895
      }
    ],
    "webp": [
      {
        "url": "/_optimized/gallery/featured/CR7_9461-480.webp",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9461-720.webp",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9461-960.webp",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9461-1200.webp",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9461-3895.webp",
        "width": 3895
      }
    ],
    "avif": [
      {
        "url": "/_optimized/gallery/featured/CR7_9461-480.avif",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9461-720.avif",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9461-960.avif",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9461-1200.avif",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9461-3895.avif",
        "width": 3895
      }
    ]
  },
  {
    "width": 3954,
    "height": 4943,
    "jpg": [
      {
        "url": "/_optimized/gallery/featured/CR7_9475-480.jpg",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9475-720.jpg",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9475-960.jpg",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9475-1200.jpg",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9475-3954.jpg",
        "width": 3954
      }
    ],
    "webp": [
      {
        "url": "/_optimized/gallery/featured/CR7_9475-480.webp",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9475-720.webp",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9475-960.webp",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9475-1200.webp",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9475-3954.webp",
        "width": 3954
      }
    ],
    "avif": [
      {
        "url": "/_optimized/gallery/featured/CR7_9475-480.avif",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9475-720.avif",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9475-960.avif",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9475-1200.avif",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9475-3954.avif",
        "width": 3954
      }
    ]
  },
  {
    "width": 4314,
    "height": 6471,
    "jpg": [
      {
        "url": "/_optimized/gallery/featured/CR7_9821-480.jpg",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9821-720.jpg",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9821-960.jpg",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9821-1200.jpg",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9821-4314.jpg",
        "width": 4314
      }
    ],
    "webp": [
      {
        "url": "/_optimized/gallery/featured/CR7_9821-480.webp",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9821-720.webp",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9821-960.webp",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9821-1200.webp",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9821-4314.webp",
        "width": 4314
      }
    ],
    "avif": [
      {
        "url": "/_optimized/gallery/featured/CR7_9821-480.avif",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9821-720.avif",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9821-960.avif",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9821-1200.avif",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9821-4314.avif",
        "width": 4314
      }
    ]
  },
  {
    "width": 4397,
    "height": 3518,
    "jpg": [
      {
        "url": "/_optimized/gallery/featured/CR7_9862-480.jpg",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9862-720.jpg",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9862-960.jpg",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9862-1200.jpg",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9862-4397.jpg",
        "width": 4397
      }
    ],
    "webp": [
      {
        "url": "/_optimized/gallery/featured/CR7_9862-480.webp",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9862-720.webp",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9862-960.webp",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9862-1200.webp",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9862-4397.webp",
        "width": 4397
      }
    ],
    "avif": [
      {
        "url": "/_optimized/gallery/featured/CR7_9862-480.avif",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9862-720.avif",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9862-960.avif",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9862-1200.avif",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9862-4397.avif",
        "width": 4397
      }
    ]
  },
  {
    "width": 4029,
    "height": 5036,
    "jpg": [
      {
        "url": "/_optimized/gallery/featured/CR7_9884-480.jpg",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9884-720.jpg",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9884-960.jpg",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9884-1200.jpg",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9884-4029.jpg",
        "width": 4029
      }
    ],
    "webp": [
      {
        "url": "/_optimized/gallery/featured/CR7_9884-480.webp",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9884-720.webp",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9884-960.webp",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9884-1200.webp",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9884-4029.webp",
        "width": 4029
      }
    ],
    "avif": [
      {
        "url": "/_optimized/gallery/featured/CR7_9884-480.avif",
        "width": 480
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9884-720.avif",
        "width": 720
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9884-960.avif",
        "width": 960
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9884-1200.avif",
        "width": 1200
      },
      {
        "url": "/_optimized/gallery/featured/CR7_9884-4029.avif",
        "width": 4029
      }
    ]
  }
];

export const genrePublicImages: Record<string, PublicImage[]> = {
  "bw": [
    {
      "width": 4000,
      "height": 5000,
      "jpg": [
        {
          "url": "/_optimized/gallery/bw/1734065475526-303611542-480.jpg",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/bw/1734065475526-303611542-720.jpg",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/bw/1734065475526-303611542-960.jpg",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/bw/1734065475526-303611542-1200.jpg",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/bw/1734065475526-303611542-4000.jpg",
          "width": 4000
        }
      ],
      "webp": [
        {
          "url": "/_optimized/gallery/bw/1734065475526-303611542-480.webp",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/bw/1734065475526-303611542-720.webp",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/bw/1734065475526-303611542-960.webp",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/bw/1734065475526-303611542-1200.webp",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/bw/1734065475526-303611542-4000.webp",
          "width": 4000
        }
      ],
      "avif": [
        {
          "url": "/_optimized/gallery/bw/1734065475526-303611542-480.avif",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/bw/1734065475526-303611542-720.avif",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/bw/1734065475526-303611542-960.avif",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/bw/1734065475526-303611542-1200.avif",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/bw/1734065475526-303611542-4000.avif",
          "width": 4000
        }
      ]
    },
    {
      "width": 3450,
      "height": 2300,
      "jpg": [
        {
          "url": "/_optimized/gallery/bw/1734065564880-710151625-480.jpg",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/bw/1734065564880-710151625-720.jpg",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/bw/1734065564880-710151625-960.jpg",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/bw/1734065564880-710151625-1200.jpg",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/bw/1734065564880-710151625-3450.jpg",
          "width": 3450
        }
      ],
      "webp": [
        {
          "url": "/_optimized/gallery/bw/1734065564880-710151625-480.webp",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/bw/1734065564880-710151625-720.webp",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/bw/1734065564880-710151625-960.webp",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/bw/1734065564880-710151625-1200.webp",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/bw/1734065564880-710151625-3450.webp",
          "width": 3450
        }
      ],
      "avif": [
        {
          "url": "/_optimized/gallery/bw/1734065564880-710151625-480.avif",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/bw/1734065564880-710151625-720.avif",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/bw/1734065564880-710151625-960.avif",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/bw/1734065564880-710151625-1200.avif",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/bw/1734065564880-710151625-3450.avif",
          "width": 3450
        }
      ]
    },
    {
      "width": 4000,
      "height": 6000,
      "jpg": [
        {
          "url": "/_optimized/gallery/bw/1734065615999-283697376-480.jpg",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/bw/1734065615999-283697376-720.jpg",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/bw/1734065615999-283697376-960.jpg",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/bw/1734065615999-283697376-1200.jpg",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/bw/1734065615999-283697376-4000.jpg",
          "width": 4000
        }
      ],
      "webp": [
        {
          "url": "/_optimized/gallery/bw/1734065615999-283697376-480.webp",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/bw/1734065615999-283697376-720.webp",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/bw/1734065615999-283697376-960.webp",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/bw/1734065615999-283697376-1200.webp",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/bw/1734065615999-283697376-4000.webp",
          "width": 4000
        }
      ],
      "avif": [
        {
          "url": "/_optimized/gallery/bw/1734065615999-283697376-480.avif",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/bw/1734065615999-283697376-720.avif",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/bw/1734065615999-283697376-960.avif",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/bw/1734065615999-283697376-1200.avif",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/bw/1734065615999-283697376-4000.avif",
          "width": 4000
        }
      ]
    },
    {
      "width": 3954,
      "height": 4943,
      "jpg": [
        {
          "url": "/_optimized/gallery/bw/CR7_0410-480.jpg",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/bw/CR7_0410-720.jpg",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/bw/CR7_0410-960.jpg",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/bw/CR7_0410-1200.jpg",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/bw/CR7_0410-3954.jpg",
          "width": 3954
        }
      ],
      "webp": [
        {
          "url": "/_optimized/gallery/bw/CR7_0410-480.webp",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/bw/CR7_0410-720.webp",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/bw/CR7_0410-960.webp",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/bw/CR7_0410-1200.webp",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/bw/CR7_0410-3954.webp",
          "width": 3954
        }
      ],
      "avif": [
        {
          "url": "/_optimized/gallery/bw/CR7_0410-480.avif",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/bw/CR7_0410-720.avif",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/bw/CR7_0410-960.avif",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/bw/CR7_0410-1200.avif",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/bw/CR7_0410-3954.avif",
          "width": 3954
        }
      ]
    },
    {
      "width": 4233,
      "height": 5291,
      "jpg": [
        {
          "url": "/_optimized/gallery/bw/CR7_0412-480.jpg",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/bw/CR7_0412-720.jpg",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/bw/CR7_0412-960.jpg",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/bw/CR7_0412-1200.jpg",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/bw/CR7_0412-4233.jpg",
          "width": 4233
        }
      ],
      "webp": [
        {
          "url": "/_optimized/gallery/bw/CR7_0412-480.webp",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/bw/CR7_0412-720.webp",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/bw/CR7_0412-960.webp",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/bw/CR7_0412-1200.webp",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/bw/CR7_0412-4233.webp",
          "width": 4233
        }
      ],
      "avif": [
        {
          "url": "/_optimized/gallery/bw/CR7_0412-480.avif",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/bw/CR7_0412-720.avif",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/bw/CR7_0412-960.avif",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/bw/CR7_0412-1200.avif",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/bw/CR7_0412-4233.avif",
          "width": 4233
        }
      ]
    },
    {
      "width": 5334,
      "height": 4267,
      "jpg": [
        {
          "url": "/_optimized/gallery/bw/CR7_7766-480.jpg",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/bw/CR7_7766-720.jpg",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/bw/CR7_7766-960.jpg",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/bw/CR7_7766-1200.jpg",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/bw/CR7_7766-5334.jpg",
          "width": 5334
        }
      ],
      "webp": [
        {
          "url": "/_optimized/gallery/bw/CR7_7766-480.webp",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/bw/CR7_7766-720.webp",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/bw/CR7_7766-960.webp",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/bw/CR7_7766-1200.webp",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/bw/CR7_7766-5334.webp",
          "width": 5334
        }
      ],
      "avif": [
        {
          "url": "/_optimized/gallery/bw/CR7_7766-480.avif",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/bw/CR7_7766-720.avif",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/bw/CR7_7766-960.avif",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/bw/CR7_7766-1200.avif",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/bw/CR7_7766-5334.avif",
          "width": 5334
        }
      ]
    },
    {
      "width": 4381,
      "height": 6571,
      "jpg": [
        {
          "url": "/_optimized/gallery/bw/CR7_9705-480.jpg",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/bw/CR7_9705-720.jpg",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/bw/CR7_9705-960.jpg",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/bw/CR7_9705-1200.jpg",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/bw/CR7_9705-4381.jpg",
          "width": 4381
        }
      ],
      "webp": [
        {
          "url": "/_optimized/gallery/bw/CR7_9705-480.webp",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/bw/CR7_9705-720.webp",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/bw/CR7_9705-960.webp",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/bw/CR7_9705-1200.webp",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/bw/CR7_9705-4381.webp",
          "width": 4381
        }
      ],
      "avif": [
        {
          "url": "/_optimized/gallery/bw/CR7_9705-480.avif",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/bw/CR7_9705-720.avif",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/bw/CR7_9705-960.avif",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/bw/CR7_9705-1200.avif",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/bw/CR7_9705-4381.avif",
          "width": 4381
        }
      ]
    }
  ],
  "portraits": [
    {
      "width": 3790,
      "height": 4737,
      "jpg": [
        {
          "url": "/_optimized/gallery/portraits/1733012032458-223128579-480.jpg",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/portraits/1733012032458-223128579-720.jpg",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/portraits/1733012032458-223128579-960.jpg",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/portraits/1733012032458-223128579-1200.jpg",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/portraits/1733012032458-223128579-3790.jpg",
          "width": 3790
        }
      ],
      "webp": [
        {
          "url": "/_optimized/gallery/portraits/1733012032458-223128579-480.webp",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/portraits/1733012032458-223128579-720.webp",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/portraits/1733012032458-223128579-960.webp",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/portraits/1733012032458-223128579-1200.webp",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/portraits/1733012032458-223128579-3790.webp",
          "width": 3790
        }
      ],
      "avif": [
        {
          "url": "/_optimized/gallery/portraits/1733012032458-223128579-480.avif",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/portraits/1733012032458-223128579-720.avif",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/portraits/1733012032458-223128579-960.avif",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/portraits/1733012032458-223128579-1200.avif",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/portraits/1733012032458-223128579-3790.avif",
          "width": 3790
        }
      ]
    },
    {
      "width": 4000,
      "height": 5000,
      "jpg": [
        {
          "url": "/_optimized/gallery/portraits/1734065475526-303611542-480.jpg",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/portraits/1734065475526-303611542-720.jpg",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/portraits/1734065475526-303611542-960.jpg",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/portraits/1734065475526-303611542-1200.jpg",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/portraits/1734065475526-303611542-4000.jpg",
          "width": 4000
        }
      ],
      "webp": [
        {
          "url": "/_optimized/gallery/portraits/1734065475526-303611542-480.webp",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/portraits/1734065475526-303611542-720.webp",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/portraits/1734065475526-303611542-960.webp",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/portraits/1734065475526-303611542-1200.webp",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/portraits/1734065475526-303611542-4000.webp",
          "width": 4000
        }
      ],
      "avif": [
        {
          "url": "/_optimized/gallery/portraits/1734065475526-303611542-480.avif",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/portraits/1734065475526-303611542-720.avif",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/portraits/1734065475526-303611542-960.avif",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/portraits/1734065475526-303611542-1200.avif",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/portraits/1734065475526-303611542-4000.avif",
          "width": 4000
        }
      ]
    },
    {
      "width": 6450,
      "height": 4338,
      "jpg": [
        {
          "url": "/_optimized/gallery/portraits/1734065686566-562344094-480.jpg",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/portraits/1734065686566-562344094-720.jpg",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/portraits/1734065686566-562344094-960.jpg",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/portraits/1734065686566-562344094-1200.jpg",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/portraits/1734065686566-562344094-6450.jpg",
          "width": 6450
        }
      ],
      "webp": [
        {
          "url": "/_optimized/gallery/portraits/1734065686566-562344094-480.webp",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/portraits/1734065686566-562344094-720.webp",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/portraits/1734065686566-562344094-960.webp",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/portraits/1734065686566-562344094-1200.webp",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/portraits/1734065686566-562344094-6450.webp",
          "width": 6450
        }
      ],
      "avif": [
        {
          "url": "/_optimized/gallery/portraits/1734065686566-562344094-480.avif",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/portraits/1734065686566-562344094-720.avif",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/portraits/1734065686566-562344094-960.avif",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/portraits/1734065686566-562344094-1200.avif",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/portraits/1734065686566-562344094-6450.avif",
          "width": 6450
        }
      ]
    },
    {
      "width": 3552,
      "height": 4440,
      "jpg": [
        {
          "url": "/_optimized/gallery/portraits/1734066068505-859845437-480.jpg",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/portraits/1734066068505-859845437-720.jpg",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/portraits/1734066068505-859845437-960.jpg",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/portraits/1734066068505-859845437-1200.jpg",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/portraits/1734066068505-859845437-3552.jpg",
          "width": 3552
        }
      ],
      "webp": [
        {
          "url": "/_optimized/gallery/portraits/1734066068505-859845437-480.webp",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/portraits/1734066068505-859845437-720.webp",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/portraits/1734066068505-859845437-960.webp",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/portraits/1734066068505-859845437-1200.webp",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/portraits/1734066068505-859845437-3552.webp",
          "width": 3552
        }
      ],
      "avif": [
        {
          "url": "/_optimized/gallery/portraits/1734066068505-859845437-480.avif",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/portraits/1734066068505-859845437-720.avif",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/portraits/1734066068505-859845437-960.avif",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/portraits/1734066068505-859845437-1200.avif",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/portraits/1734066068505-859845437-3552.avif",
          "width": 3552
        }
      ]
    },
    {
      "width": 4000,
      "height": 6000,
      "jpg": [
        {
          "url": "/_optimized/gallery/portraits/1734066142496-58978677-480.jpg",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/portraits/1734066142496-58978677-720.jpg",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/portraits/1734066142496-58978677-960.jpg",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/portraits/1734066142496-58978677-1200.jpg",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/portraits/1734066142496-58978677-4000.jpg",
          "width": 4000
        }
      ],
      "webp": [
        {
          "url": "/_optimized/gallery/portraits/1734066142496-58978677-480.webp",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/portraits/1734066142496-58978677-720.webp",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/portraits/1734066142496-58978677-960.webp",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/portraits/1734066142496-58978677-1200.webp",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/portraits/1734066142496-58978677-4000.webp",
          "width": 4000
        }
      ],
      "avif": [
        {
          "url": "/_optimized/gallery/portraits/1734066142496-58978677-480.avif",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/portraits/1734066142496-58978677-720.avif",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/portraits/1734066142496-58978677-960.avif",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/portraits/1734066142496-58978677-1200.avif",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/portraits/1734066142496-58978677-4000.avif",
          "width": 4000
        }
      ]
    },
    {
      "width": 6000,
      "height": 4000,
      "jpg": [
        {
          "url": "/_optimized/gallery/portraits/1734066180384-503132957-480.jpg",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/portraits/1734066180384-503132957-720.jpg",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/portraits/1734066180384-503132957-960.jpg",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/portraits/1734066180384-503132957-1200.jpg",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/portraits/1734066180384-503132957-6000.jpg",
          "width": 6000
        }
      ],
      "webp": [
        {
          "url": "/_optimized/gallery/portraits/1734066180384-503132957-480.webp",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/portraits/1734066180384-503132957-720.webp",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/portraits/1734066180384-503132957-960.webp",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/portraits/1734066180384-503132957-1200.webp",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/portraits/1734066180384-503132957-6000.webp",
          "width": 6000
        }
      ],
      "avif": [
        {
          "url": "/_optimized/gallery/portraits/1734066180384-503132957-480.avif",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/portraits/1734066180384-503132957-720.avif",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/portraits/1734066180384-503132957-960.avif",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/portraits/1734066180384-503132957-1200.avif",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/portraits/1734066180384-503132957-6000.avif",
          "width": 6000
        }
      ]
    },
    {
      "width": 4000,
      "height": 5000,
      "jpg": [
        {
          "url": "/gallery/portraits/1734066888245-167850319.jpg",
          "width": 4000
        }
      ],
      "webp": [],
      "avif": []
    },
    {
      "width": 2935,
      "height": 3669,
      "jpg": [
        {
          "url": "/_optimized/gallery/portraits/1734066888249-889393263-480.jpg",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/portraits/1734066888249-889393263-720.jpg",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/portraits/1734066888249-889393263-960.jpg",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/portraits/1734066888249-889393263-1200.jpg",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/portraits/1734066888249-889393263-2935.jpg",
          "width": 2935
        }
      ],
      "webp": [
        {
          "url": "/_optimized/gallery/portraits/1734066888249-889393263-480.webp",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/portraits/1734066888249-889393263-720.webp",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/portraits/1734066888249-889393263-960.webp",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/portraits/1734066888249-889393263-1200.webp",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/portraits/1734066888249-889393263-2935.webp",
          "width": 2935
        }
      ],
      "avif": []
    },
    {
      "width": 3795,
      "height": 4744,
      "jpg": [
        {
          "url": "/_optimized/gallery/portraits/1734066888251-277521743-480.jpg",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/portraits/1734066888251-277521743-720.jpg",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/portraits/1734066888251-277521743-960.jpg",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/portraits/1734066888251-277521743-1200.jpg",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/portraits/1734066888251-277521743-3795.jpg",
          "width": 3795
        }
      ],
      "webp": [
        {
          "url": "/_optimized/gallery/portraits/1734066888251-277521743-480.webp",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/portraits/1734066888251-277521743-720.webp",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/portraits/1734066888251-277521743-960.webp",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/portraits/1734066888251-277521743-1200.webp",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/portraits/1734066888251-277521743-3795.webp",
          "width": 3795
        }
      ],
      "avif": []
    },
    {
      "width": 4151,
      "height": 3321,
      "jpg": [
        {
          "url": "/_optimized/gallery/portraits/1734066888475-77171774-480.jpg",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/portraits/1734066888475-77171774-720.jpg",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/portraits/1734066888475-77171774-960.jpg",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/portraits/1734066888475-77171774-1200.jpg",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/portraits/1734066888475-77171774-4151.jpg",
          "width": 4151
        }
      ],
      "webp": [
        {
          "url": "/_optimized/gallery/portraits/1734066888475-77171774-480.webp",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/portraits/1734066888475-77171774-720.webp",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/portraits/1734066888475-77171774-960.webp",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/portraits/1734066888475-77171774-1200.webp",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/portraits/1734066888475-77171774-4151.webp",
          "width": 4151
        }
      ],
      "avif": []
    },
    {
      "width": 4640,
      "height": 5800,
      "jpg": [
        {
          "url": "/_optimized/gallery/portraits/CR7_7767-480.jpg",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/portraits/CR7_7767-720.jpg",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/portraits/CR7_7767-960.jpg",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/portraits/CR7_7767-1200.jpg",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/portraits/CR7_7767-4640.jpg",
          "width": 4640
        }
      ],
      "webp": [
        {
          "url": "/_optimized/gallery/portraits/CR7_7767-480.webp",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/portraits/CR7_7767-720.webp",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/portraits/CR7_7767-960.webp",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/portraits/CR7_7767-1200.webp",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/portraits/CR7_7767-4640.webp",
          "width": 4640
        }
      ],
      "avif": []
    },
    {
      "width": 3822,
      "height": 4777,
      "jpg": [
        {
          "url": "/_optimized/gallery/portraits/CR7_7771-480.jpg",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/portraits/CR7_7771-720.jpg",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/portraits/CR7_7771-960.jpg",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/portraits/CR7_7771-1200.jpg",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/portraits/CR7_7771-3822.jpg",
          "width": 3822
        }
      ],
      "webp": [
        {
          "url": "/_optimized/gallery/portraits/CR7_7771-480.webp",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/portraits/CR7_7771-720.webp",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/portraits/CR7_7771-960.webp",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/portraits/CR7_7771-1200.webp",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/portraits/CR7_7771-3822.webp",
          "width": 3822
        }
      ],
      "avif": []
    }
  ],
  "landscape": [
    {
      "width": 3950,
      "height": 4937,
      "jpg": [
        {
          "url": "/_optimized/gallery/landscape/CR7_9752-480.jpg",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/landscape/CR7_9752-720.jpg",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/landscape/CR7_9752-960.jpg",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/landscape/CR7_9752-1200.jpg",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/landscape/CR7_9752-3950.jpg",
          "width": 3950
        }
      ],
      "webp": [
        {
          "url": "/_optimized/gallery/landscape/CR7_9752-480.webp",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/landscape/CR7_9752-720.webp",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/landscape/CR7_9752-960.webp",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/landscape/CR7_9752-1200.webp",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/landscape/CR7_9752-3950.webp",
          "width": 3950
        }
      ],
      "avif": [
        {
          "url": "/_optimized/gallery/landscape/CR7_9752-480.avif",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/landscape/CR7_9752-720.avif",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/landscape/CR7_9752-960.avif",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/landscape/CR7_9752-1200.avif",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/landscape/CR7_9752-3950.avif",
          "width": 3950
        }
      ]
    },
    {
      "width": 4478,
      "height": 5598,
      "jpg": [
        {
          "url": "/_optimized/gallery/landscape/CR7_9769-480.jpg",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/landscape/CR7_9769-720.jpg",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/landscape/CR7_9769-960.jpg",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/landscape/CR7_9769-1200.jpg",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/landscape/CR7_9769-4478.jpg",
          "width": 4478
        }
      ],
      "webp": [
        {
          "url": "/_optimized/gallery/landscape/CR7_9769-480.webp",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/landscape/CR7_9769-720.webp",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/landscape/CR7_9769-960.webp",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/landscape/CR7_9769-1200.webp",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/landscape/CR7_9769-4478.webp",
          "width": 4478
        }
      ],
      "avif": [
        {
          "url": "/_optimized/gallery/landscape/CR7_9769-480.avif",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/landscape/CR7_9769-720.avif",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/landscape/CR7_9769-960.avif",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/landscape/CR7_9769-1200.avif",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/landscape/CR7_9769-4478.avif",
          "width": 4478
        }
      ]
    }
  ],
  "street": [
    {
      "width": 3450,
      "height": 2300,
      "jpg": [
        {
          "url": "/_optimized/gallery/street/1734065564880-710151625-480.jpg",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/street/1734065564880-710151625-720.jpg",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/street/1734065564880-710151625-960.jpg",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/street/1734065564880-710151625-1200.jpg",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/street/1734065564880-710151625-3450.jpg",
          "width": 3450
        }
      ],
      "webp": [
        {
          "url": "/_optimized/gallery/street/1734065564880-710151625-480.webp",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/street/1734065564880-710151625-720.webp",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/street/1734065564880-710151625-960.webp",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/street/1734065564880-710151625-1200.webp",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/street/1734065564880-710151625-3450.webp",
          "width": 3450
        }
      ],
      "avif": [
        {
          "url": "/_optimized/gallery/street/1734065564880-710151625-480.avif",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/street/1734065564880-710151625-720.avif",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/street/1734065564880-710151625-960.avif",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/street/1734065564880-710151625-1200.avif",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/street/1734065564880-710151625-3450.avif",
          "width": 3450
        }
      ]
    },
    {
      "width": 5377,
      "height": 3585,
      "jpg": [
        {
          "url": "/_optimized/gallery/street/1734065599018-930614260-480.jpg",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/street/1734065599018-930614260-720.jpg",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/street/1734065599018-930614260-960.jpg",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/street/1734065599018-930614260-1200.jpg",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/street/1734065599018-930614260-5377.jpg",
          "width": 5377
        }
      ],
      "webp": [
        {
          "url": "/_optimized/gallery/street/1734065599018-930614260-480.webp",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/street/1734065599018-930614260-720.webp",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/street/1734065599018-930614260-960.webp",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/street/1734065599018-930614260-1200.webp",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/street/1734065599018-930614260-5377.webp",
          "width": 5377
        }
      ],
      "avif": [
        {
          "url": "/_optimized/gallery/street/1734065599018-930614260-480.avif",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/street/1734065599018-930614260-720.avif",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/street/1734065599018-930614260-960.avif",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/street/1734065599018-930614260-1200.avif",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/street/1734065599018-930614260-5377.avif",
          "width": 5377
        }
      ]
    },
    {
      "width": 4000,
      "height": 6000,
      "jpg": [
        {
          "url": "/_optimized/gallery/street/1734065615999-283697376-480.jpg",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/street/1734065615999-283697376-720.jpg",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/street/1734065615999-283697376-960.jpg",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/street/1734065615999-283697376-1200.jpg",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/street/1734065615999-283697376-4000.jpg",
          "width": 4000
        }
      ],
      "webp": [
        {
          "url": "/_optimized/gallery/street/1734065615999-283697376-480.webp",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/street/1734065615999-283697376-720.webp",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/street/1734065615999-283697376-960.webp",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/street/1734065615999-283697376-1200.webp",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/street/1734065615999-283697376-4000.webp",
          "width": 4000
        }
      ],
      "avif": [
        {
          "url": "/_optimized/gallery/street/1734065615999-283697376-480.avif",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/street/1734065615999-283697376-720.avif",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/street/1734065615999-283697376-960.avif",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/street/1734065615999-283697376-1200.avif",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/street/1734065615999-283697376-4000.avif",
          "width": 4000
        }
      ]
    },
    {
      "width": 3954,
      "height": 4943,
      "jpg": [
        {
          "url": "/_optimized/gallery/street/CR7_0410-480.jpg",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/street/CR7_0410-720.jpg",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/street/CR7_0410-960.jpg",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/street/CR7_0410-1200.jpg",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/street/CR7_0410-3954.jpg",
          "width": 3954
        }
      ],
      "webp": [
        {
          "url": "/_optimized/gallery/street/CR7_0410-480.webp",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/street/CR7_0410-720.webp",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/street/CR7_0410-960.webp",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/street/CR7_0410-1200.webp",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/street/CR7_0410-3954.webp",
          "width": 3954
        }
      ],
      "avif": [
        {
          "url": "/_optimized/gallery/street/CR7_0410-480.avif",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/street/CR7_0410-720.avif",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/street/CR7_0410-960.avif",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/street/CR7_0410-1200.avif",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/street/CR7_0410-3954.avif",
          "width": 3954
        }
      ]
    },
    {
      "width": 6960,
      "height": 4640,
      "jpg": [
        {
          "url": "/_optimized/gallery/street/CR7_7733-480.jpg",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/street/CR7_7733-720.jpg",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/street/CR7_7733-960.jpg",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/street/CR7_7733-1200.jpg",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/street/CR7_7733-6960.jpg",
          "width": 6960
        }
      ],
      "webp": [
        {
          "url": "/_optimized/gallery/street/CR7_7733-480.webp",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/street/CR7_7733-720.webp",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/street/CR7_7733-960.webp",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/street/CR7_7733-1200.webp",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/street/CR7_7733-6960.webp",
          "width": 6960
        }
      ],
      "avif": [
        {
          "url": "/_optimized/gallery/street/CR7_7733-480.avif",
          "width": 480
        },
        {
          "url": "/_optimized/gallery/street/CR7_7733-720.avif",
          "width": 720
        },
        {
          "url": "/_optimized/gallery/street/CR7_7733-960.avif",
          "width": 960
        },
        {
          "url": "/_optimized/gallery/street/CR7_7733-1200.avif",
          "width": 1200
        },
        {
          "url": "/_optimized/gallery/street/CR7_7733-6960.avif",
          "width": 6960
        }
      ]
    }
  ]
};
