/* eslint-disable */
// Auto-generated by scripts/generate-public-media-manifest.mjs — do not edit.

export interface PublicImage {
  readonly url: string;
  readonly width: number;
  readonly height: number;
}

export const heroGallery: PublicImage[] = [
  {
    "url": "/hero/1734066180384-503132957.jpg",
    "width": 6000,
    "height": 4000
  }
];

export const featuredGallery: PublicImage[] = [
  {
    "url": "/gallery/featured/1734065395770-537681133.jpg",
    "width": 3280,
    "height": 4100
  },
  {
    "url": "/gallery/featured/1734065508950-385634406.jpg",
    "width": 4000,
    "height": 5000
  },
  {
    "url": "/gallery/featured/1734066160338-665205057.jpg",
    "width": 4000,
    "height": 6000
  },
  {
    "url": "/gallery/featured/1734066888247-726289103.jpg",
    "width": 3527,
    "height": 4409
  },
  {
    "url": "/gallery/featured/1734066888253-502748387.jpg",
    "width": 3414,
    "height": 4267
  },
  {
    "url": "/gallery/featured/CR7_9082.jpg",
    "width": 3709,
    "height": 5563
  },
  {
    "url": "/gallery/featured/CR7_9094.jpg",
    "width": 4640,
    "height": 6960
  },
  {
    "url": "/gallery/featured/CR7_9426.jpg",
    "width": 4469,
    "height": 5586
  },
  {
    "url": "/gallery/featured/CR7_9461.jpg",
    "width": 3895,
    "height": 5842
  },
  {
    "url": "/gallery/featured/CR7_9475.jpg",
    "width": 3954,
    "height": 4943
  },
  {
    "url": "/gallery/featured/CR7_9821.jpg",
    "width": 4314,
    "height": 6471
  },
  {
    "url": "/gallery/featured/CR7_9862.jpg",
    "width": 4397,
    "height": 3518
  },
  {
    "url": "/gallery/featured/CR7_9884.jpg",
    "width": 4029,
    "height": 5036
  }
];

export const genrePublicUrls: Record<string, string[]> = {
  "bw": [
    "/gallery/bw/1734065475526-303611542.jpg",
    "/gallery/bw/1734065564880-710151625.jpg",
    "/gallery/bw/1734065615999-283697376.jpg",
    "/gallery/bw/CR7_0410.jpg",
    "/gallery/bw/CR7_0412.jpg",
    "/gallery/bw/CR7_7766.jpg",
    "/gallery/bw/CR7_9705.jpg"
  ],
  "portraits": [
    "/gallery/portraits/1733012032458-223128579.JPG",
    "/gallery/portraits/1734065475526-303611542.jpg",
    "/gallery/portraits/1734065686566-562344094.jpg",
    "/gallery/portraits/1734066068505-859845437.jpg",
    "/gallery/portraits/1734066142496-58978677.jpg",
    "/gallery/portraits/1734066180384-503132957.jpg",
    "/gallery/portraits/1734066888245-167850319.jpg",
    "/gallery/portraits/1734066888249-889393263.jpg",
    "/gallery/portraits/1734066888251-277521743.jpg",
    "/gallery/portraits/1734066888475-77171774.jpg",
    "/gallery/portraits/CR7_7767.jpg",
    "/gallery/portraits/CR7_7771.jpg"
  ],
  "landscape": [
    "/gallery/landscape/CR7_9752.jpg",
    "/gallery/landscape/CR7_9769.jpg"
  ],
  "street": [
    "/gallery/street/1734065564880-710151625.jpg",
    "/gallery/street/1734065599018-930614260.jpg",
    "/gallery/street/1734065615999-283697376.jpg",
    "/gallery/street/CR7_0410.jpg",
    "/gallery/street/CR7_7733.jpg"
  ]
};
